apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: blog-east2
  namespace: wordpress
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - {key: name, operator: In, values: ["east2"]}

