apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: standby
  namespace: rook-ceph
spec:
  clusterConditions:
   - type: OK
  clusterSelector:
    matchExpressions: []
    matchLabels:
      name: "east1"
  clusterReplicas: 1
